name: TENARAI

on:
  schedule:
    - cron: '*/6 * * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show log
      run: git log
    - name: tagging
      run: |
        TAGNAME=actions/${GITHUB_WORKFLOW}/`date "+%Y%m%dT%H%M%S"`
        echo git tag "${TAGNAME}"
        git tag "${TAGNAME}"
        git push origin "${TAGNAME}"
