on:
  push:
    branches:
      - gradle
jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/modules-2/modules-2.lock
            !~/.gradle/caches/modules-2/gc.properties
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - run: |
          ls -al ~/.gradle/caches/modules-2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          ./gradlew build
          ls -al ~/.gradle/caches/modules-2

