on:
  push:
    branches:
      - gradle
jobs:
  my-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          ./gradlew build
          ls -al ~/.gradle/caches
          ls -al ~/.gradle/caches/modules-2

