name: タグを作るよ

on:
  push:
    branches:
      - tagging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Show log
        run: git log
      - id: generate-tag-name
        run: |
          TAGNAME=actions/${GITHUB_WORKFLOW}/`date "+%Y%m%dT%H%M%S"`
          echo "::set-env name=TAGNAME::${TAGNAME}"
      - name: create tag and push
        run: |
          echo git tag "${TAGNAME}"
          git tag "${TAGNAME}"
          PUSHURL="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git push ${PUSHURL} ${TAGNAME}

