name: タグを作るよ

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show log
      run: git log
    - name: tagを作ってpush
      run: |
        TAGNAME=actions/${GITHUB_WORKFLOW}/`date "+%Y%m%dT%H%M%S"`
        echo git tag "${TAGNAME}"
        git tag "${TAGNAME}"
        PUSHURL="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
        git push ${PUSHURL} ${TAGNAME}
