name: こんにちは

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - actions/checkout@v2
      - name: Print a greeting
        run: |
          echo hello world.
      - name: curl
        run: curl --help
      - name: jq
        run: jq --help
      - name: latest tag
        run: |
          curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r ".tag_name"


