name: こんにちは

on:
  push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo hello world.
      - name: curl
        run: curl --help
      - name: jq
        run: jq --help

