name: じっけんじょう

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: コマンド実行
        run: |
          echo hello world.
      - name: コードを取ってくる
        uses: actions/checkout@v2
      - name: GitHub APIでlatestリリースのtag取得
        run: |
          curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r ".tag_name"


