name: TENARAI

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: パブリックなActionを使う
      id: public-hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'public'
    - name: このリポジトリのActionを使う
      id: private-hello
      uses: ./hello-world-docker-action
      with:
        who-to-greet: 'private'
    - name: Get the output time
      run: echo "The time was ${{ steps.public-hello.outputs.time }}"
    - name: Get the output time
      run: echo "The time was ${{ steps.private-hello.outputs.time }}"