name: Docker actionを使ってみる

on: [push]

jobs:
  public-hello-job:
    runs-on: ubuntu-latest
    name: 公開されているActionを使う
    steps:
    - name: 公開されてるのを実行
      id: public-hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'public'
    - name: 実行時間の出力
      run: echo "The time was ${{ steps.public-hello.outputs.time }}" > time.txt
    - name: 実行時間のアップロード
      uses: actions/upload-artifact@v1
      with:
        name: public-output
        path: time.txt
  private-hello-job:
    runs-on: ubuntu-latest
    name: このリポジトリのActionを使う
    steps:
    - name: このリポジトリのコードを取得
      uses: actions/checkout@v1
    - name: Dockerfileをビルドして実行
      id: private-hello
      uses: ./hello-world-docker-action
      with:
        who-to-greet: 'private'
    - name: 実行時間の出力
      run: echo "The time was ${{ steps.private-hello.outputs.time }}" > time.txt
    - name: 実行時間のアップロード
      uses: actions/upload-artifact@v1
      with:
        name: private-output
        path: time.txt
  echo-job:
    runs-on: ubuntu-latest
    name: 結果を出力する
    needs: [public-hello-job, private-hello-job]
    steps:
      - name: 結果取得
        uses: actions/download-artifact@v1
        with:
          name: public-output
      - name: 結果取得
        uses: actions/download-artifact@v1
        with:
          name: private-output
      - name: 出力
        run: |
          cat public-output/time.txt
          cat private-output/time.txt
