name: Docker actionを使ってみる

on: [push]

jobs:
  public-hello-job:
    runs-on: ubuntu-latest
    name: 公開されているActionを使う
    steps:
    - name: 
      id: public-hello
      uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: 'public'
  private-hello-job:
    runs-on: ubuntu-latest
    name: このリポジトリのActionを使う
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: 
      id: private-hello
      uses: ./hello-world-docker-action
      with:
        who-to-greet: 'private'
  echo-job:
    runs-on: ubuntu-latest
    name: 結果を出力する
    needs: [public-hello-job, private-hello-job]
    steps:
    - name: Get the output time
      run: echo "The time was ${{ steps.public-hello.outputs.time }}"
    - name: Get the output time
      run: echo "The time was ${{ steps.private-hello.outputs.time }}"
