name: PullRequestで動くもの

on:
  pull_request:
    paths:
    - '!**/piyo/**'

jobs:
  sample:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: echo
        run: echo "pull requset"
