name: masterの更新で動く

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    name: HelloWorld
    runs-on: ubuntu-latest
    steps:
      - name: コマンド実行
        run: |
          echo hello world.
  jikken:
    name: じっけん
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_USERNAME: じっけん@GitHubActions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
