name: masterの更新で動く

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    name: HelloWorld
    runs-on: ubuntu-latest
    steps:
      - name: コマンド実行
        run: |
          echo hello world.
  slack:
    name: Slackに通知
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Hello, World!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
  hello-js:
    name: HelloJavaScriptAction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: inoke JavaScript
        uses: ./github/actions/hello-javascript-action
