name: masterの更新で動く

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    name: HelloWorld
    runs-on: ubuntu-latest
    steps:
      - name: コマンド実行
        run: |
          echo hello world.
  jikken:
    name: じっけん
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Hello, World!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

