name: リリースで動くもの

# https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
#
# draftでは動かない。
#
# typeを指定しないと全てで動くらしい。
# 何も指定しないと3回動くが、ドキュメントにある全てを列挙しても2回しか動かない不思議。
# あとリリース削除してもdeleted動かない。
# ついでに一回公開したリリースってDraftに戻せないからunpublishedって何なの。
# とはいえ実際使うのは [published] くらいだろう。
# 
# types:
#  - published
#  - unpublished
#  - created
#  - edited
#  - deleted
#  - prereleased
# 
# 環境変数に以下が設定される。
# - GITHUB_SHA: リリースタグのSHA
# - GITHUB_REF: タグ名 (refs/tags/{タグ名}) ……タグ名だけがよかったなぁ。
#
# GitHub Actionsで作ったリリース( `on_release.yml` 参照) からはトリガーされない。
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#about-workflow-events
# > An action in a workflow run can't trigger a new workflow run.

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_SHA}
      - run: echo ${GITHUB_REF}
