name: タグ作ったら動く

on:
  push:
    tags:
      - 'actions/v*'

jobs:
  release:
    name: リリース作成
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v2
      - name: リポジトリのログ取得のためのunshallow
        run: git fetch --prune --unshallow
      - name: GitHubからlatestなリリースタグを取得
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r ".tag_name")
          echo ${latest_tag}
          echo "::set-env name=latest_tag::${latest_tag}"
      - name: リリースの内容をgitのログから作成
        id: get_body
        run: |
          echo "${latest_tag} 以降のログを取得します"
          body=$(git log --format="%s" ${latest_tag}..HEAD -- . | awk '{printf $0","}')
          echo ${body}
          echo "::set-output name=body::${body}"
      - name: リリース作成
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Draft ${{ github.ref }}
          body: ${{ steps.get_body.outputs.body }}
          draft: false
          prerelease: false

