name: リリースで動くもの

# https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
#
# draftでは動かない。
#
# typeを指定しないと全てで動く
# 
# types:
#  - published
#  - unpublished
#  - created
#  - edited
#  - deleted
#  - prereleased
# 
# 環境変数に以下が設定される。
# - GITHUB_SHA: リリースタグのSHA
# - GITHUB_REF: タグ名

on:
  release:
    types:
      - published
      - edited
      - prereleased
      - unpublished
      - deleted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_SHA}
      - run: echo ${GITHUB_REF}
