name: DockerHubのイメージを使う

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v2
      - run: |
          echo hello
          ls -al
          pwd
      - name: alpineでls
        uses: docker://alpine
        with:
          entrypoint: /bin/ls
          args: -al
      - name: alpineでpwd
        uses: docker://alpine
        with:
          entrypoint: /bin/pwd
      - name: alpineでpwd
        uses: docker://irof/rexdep
        with:
          args: '--pattern "name: (.+)" -r .github'
      - name: alpineでpwd
        working-directory: ./.github
        uses: docker://alpine
        with:
          entrypoint: /bin/pwd
