name: DockerHubのイメージを使う

on:
  push:
    branches: main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v2
      - run: |
          echo hello
          ls -al
          pwd
      - name: rexdep
        uses: docker://irof/rexdep
        with:
          args: '--pattern "^[ -]+ name: (.+)" --format dot -o graph.dot -r .github/workflows'
      - name: rexdep
        uses: docker://irof/rexdep
        with:
          entrypoint: /usr/bin/dot
          args: '-Tsvg -o graph.svg graph.dot'
      - name: push
        run: |
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add graph.svg
          git commit -m "update" --allow-empty
          git push origin main 

  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/core:2.17
        with:
          entrypoint: .github/test.sh
          # args: -f markdown -t html --self-contained --toc --toc-depth=1 --output=output/result.html ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
