name: DockerHubのイメージを使う

on:
  - workflow_dispatch
  - push: main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v2
      - run: |
          echo hello
          ls -al
          pwd
      - name: alpineでls
        uses: docker://alpine
        with:
          entrypoint: /bin/ls
          args: -al
      - name: alpineでpwd
        uses: docker://alpine
        with:
          entrypoint: /bin/pwd
      - name: rexdep
        uses: docker://irof/rexdep
        with:
          args: '--pattern "name: (.+)" --format dot -o graph.dot -r .github/workflows'
      - name: rexdep
        uses: docker://irof/rexdep
        with:
          entrypoint: /usr/bin/dot
          args: '-Tpng -o graph.svg graph.dot'
      - name: push
        run: |
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add graph.svg
          git commit -m "update"
          git push origin main 
